# Generated by Django 3.1.7 on 2021-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_remove_show_total_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='imdb_id',
            field=models.CharField(default='a', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
