# Generated by Django 3.1.7 on 2021-03-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_remove_comment_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='show.episode'),
            preserve_default=False,
        ),
    ]
