
app:
  image:
    python:3.8
  expose:
    - 8080
  volumes:
    - database_storage:/database
    - environment:/environment
    - ./application:/app
  working_dir:
    /environment
  command:
    bash -c '
      python3 -m venv /environment &&
      source /environment/bin/activate &&
      pip install -r /app/requirements.txt &&
      python /app/app.py
    '
  environment:
    - DB_SQLITE_DIR=/database
    - OMDBAPI_KEY=${OMDBAPI_KEY}
    - API_PORT=8080

