# Generated by Django 4.1.1 on 2023-09-01 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import series.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=150)),
                ("genre", models.CharField(max_length=40)),
                ("year", models.CharField(max_length=40)),
                ("imdb_id", models.CharField(max_length=15)),
                ("created_at", series.models.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated_at", series.models.DateTimeWithoutTZField(auto_now=True)),
            ],
            options={
                "db_table": "show",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_number",
                    models.IntegerField(
                        default="1",
                        validators=[
                            django.core.validators.MaxValueValidator(15),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("total_episodes", models.CharField(max_length=10)),
                ("created_at", series.models.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated_at", series.models.DateTimeWithoutTZField(auto_now=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.show"
                    ),
                ),
            ],
            options={
                "db_table": "season",
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_number",
                    models.IntegerField(
                        default="1",
                        validators=[
                            django.core.validators.MaxValueValidator(30),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("imdb_rating", models.CharField(max_length=5)),
                ("created_at", series.models.DateTimeWithoutTZField(auto_now_add=True)),
                ("updated_at", series.models.DateTimeWithoutTZField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="series.season"
                    ),
                ),
            ],
            options={
                "db_table": "episode",
            },
        ),
    ]
